version: '3.8'
services:
  app:
    build:
      context: .
      target: development
    ports:
      - "4321:4321"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
